spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:2710/EMS
spring.datasource.username=postgres
spring.datasource.password=kaushik2710
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kkahir2710@gmail.com
spring.mail.password=viqzhcoecukjyklw
spring.mail.properties.mail.smtp.auto=true
spring.mail.properties.mail.smtp.starttls.enable=true